//
//  UrlParam.swift
//  HideSeek
//
//  Created by apple on 6/22/16.
//  Copyright © 2016 mj. All rights reserved.
//

class UrlParam {
    static let GET_SETTINGS = "https://www.hideseek.cn/home/user/getSettings"
    static let LOGIN_URL = "https://www.hideseek.cn/home/user/login"
    static let REGISTER_URL = "https://www.hideseek.cn/home/user/register"
    static let REFRESH_MAP_URL = "https://www.hideseek.cn/home/map/refresh"
    static let GET_RACE_GROUP_URL = "https://www.hideseek.cn/home/friend/getRaceGroup"
    static let REFRESH_RACE_GROUP_URL = "https://www.hideseek.cn/home/friend/refreshRaceGroup"
    static let REFRESH_RECORD_URL = "https://www.hideseek.cn/home/record/refreshRecords"
    static let GET_RECORD_URL = "https://www.hideseek.cn/home/record/getRecords"
    static let SET_BOMB_URL = "https://www.hideseek.cn/home/map/setBomb"
    static let GET_GOAL_URL = "https://www.hideseek.cn/home/map/getGoal"
    static let REFRESH_PRODUCT_URL = "https://www.hideseek.cn/home/store/refreshProducts"
    static let GET_PRODUCT_URL = "https://www.hideseek.cn/home/store/getProducts"
    static let GET_REWARD_URL = "https://www.hideseek.cn/home/store/getReward"
    static let REFRESH_REWARD_URL = "https://www.hideseek.cn/home/store/refreshReward"
    static let CREATE_ORDER_URL = "https://www.hideseek.cn/home/store/createOrder"
    static let GET_PURCHASE_ORDERS_URL = "https://www.hideseek.cn/home/store/getPurchaseOrders"
    static let REFRESH_PURCHASE_ORDERS_URL = "https://www.hideseek.cn/home/store/refreshPurchaseOrders"
    static let GET_EXCHANGE_ORDERS_URL = "https://www.hideseek.cn/home/store/getExchangeOrders"
    static let REFRESH_EXCHANGE_ORDERS_URL = "https://www.hideseek.cn/home/store/refreshExchangeOrders"
    static let CREATE_EXCHANGE_ORDER_URL = "https://www.hideseek.cn/home/store/createExchangeOrder"
    static let GET_PURCHASE_ORDER_URL = "https://www.hideseek.cn/home/store/getPurchaseOrder"
    static let HIT_MONSTER_URL = "https://www.hideseek.cn/home/map/hitMonster"
    static let CHECK_IF_USER_EXIST_URL = "https://www.hideseek.cn/home/user/checkIfUserExist"
    static let UPDATE_PHOTO_URL = "https://www.hideseek.cn/home/user/updatePhotoUrl"
    static let UPDATE_NICKNAME = "https://www.hideseek.cn/home/user/updateNickname"
    static let UPDATE_SEX = "https://www.hideseek.cn/home/user/updateSex"
    static let UPDATE_REGION = "https://www.hideseek.cn/home/user/updateRegion"
    static let GET_FRIENDS_URL = "https://www.hideseek.cn/home/friend/getFriends"
    static let SEARCH_FRIENDS_URL = "https://www.hideseek.cn/home/friend/searchFriends"
    static let ADD_FRIENDS_URL = "https://www.hideseek.cn/home/friend/addFriend"
    static let SEE_MONSTER_URL = "https://www.hideseek.cn/home/map/seeMonster"
    static let GET_DANGER_WARNING_URL = "https://www.hideseek.cn/home/map/getDangerWarnings"
    static let ACCEPT_FRIEND_URL = "https://www.hideseek.cn/home/friend/acceptFriend"
    static let ADD_FEEDBACK_URL = "https://www.hideseek.cn/home/setting/addFeedback"
    static let LOGOUT_URL = "https://www.hideseek.cn/home/user/logout"
    static let UPDATE_REMARK = "https://www.hideseek.cn/home/friend/updateRemark"
    static let PURCHASE_URL = "https://www.hideseek.cn/home/store/purchase"
    static let UPDATE_PASSWORD_URL = "https://www.hideseek.cn/home/user/updatePassword"
    static let REMOVE_FRIEND_URL = "https://www.hideseek.cn/home/friend/removeFriend"
    static let UPDATE_CHANNEL_URL = "https://www.hideseek.cn/home/user/updateChannelId"
    static let GET_FRIEND_REQUESTS_URL = "https://www.hideseek.cn/home/user/getFriendRequests"
    static let UPDATE_USER_INFO_URL = "https://www.hideseek.cn/home/user/updateUserInfo"
    
    
//    static let IP_ADDRESS = "192.168.1.101"
//    static let GET_SETTINGS = "http://" + IP_ADDRESS + "/home/user/getSettings"
//    static let LOGIN_URL = "http://" + IP_ADDRESS + "/home/user/login"
//    static let REGISTER_URL = "http://" + IP_ADDRESS + "/home/user/register"
//    static let REFRESH_MAP_URL = "http://" + IP_ADDRESS + "/home/map/refresh"
//    static let GET_RACE_GROUP_URL = "http://" + IP_ADDRESS + "/home/friend/getRaceGroup"
//    static let REFRESH_RACE_GROUP_URL = "http://" + IP_ADDRESS + "/home/friend/refreshRaceGroup"
//    static let REFRESH_RECORD_URL = "http://" + IP_ADDRESS + "/home/record/refreshRecords"
//    static let GET_RECORD_URL = "http://" + IP_ADDRESS + "/home/record/getRecords"
//    static let SET_BOMB_URL = "http://" + IP_ADDRESS + "/home/map/setBomb"
//    static let GET_GOAL_URL = "http://" + IP_ADDRESS + "/home/map/getGoal"
//    static let REFRESH_PRODUCT_URL = "http://" + IP_ADDRESS + "/home/store/refreshProducts"
//    static let GET_PRODUCT_URL = "http://" + IP_ADDRESS + "/home/store/getProducts"
//    static let GET_REWARD_URL = "http://" + IP_ADDRESS + "/home/store/getReward"
//    static let REFRESH_REWARD_URL = "http://" + IP_ADDRESS + "/home/store/refreshReward"
//    static let CREATE_ORDER_URL = "http://" + IP_ADDRESS + "/home/store/createOrder"
//    static let GET_PURCHASE_ORDERS_URL = "http://" + IP_ADDRESS + "/home/store/getPurchaseOrders"
//    static let REFRESH_PURCHASE_ORDERS_URL = "http://" + IP_ADDRESS + "/home/store/refreshPurchaseOrders"
//    static let GET_EXCHANGE_ORDERS_URL = "http://" + IP_ADDRESS + "/home/store/getExchangeOrders"
//    static let REFRESH_EXCHANGE_ORDERS_URL = "http://" + IP_ADDRESS + "/home/store/refreshExchangeOrders"
//    static let CREATE_EXCHANGE_ORDER_URL = "http://" + IP_ADDRESS + "/home/store/createExchangeOrder"
//    static let GET_PURCHASE_ORDER_URL = "http://" + IP_ADDRESS + "/home/store/getPurchaseOrder"
//    static let HIT_MONSTER_URL = "http://" + IP_ADDRESS + "/home/map/hitMonster"
//    static let CHECK_IF_USER_EXIST_URL = "http://" + IP_ADDRESS + "/home/user/checkIfUserExist"
//    static let UPDATE_PHOTO_URL = "http://" + IP_ADDRESS + "/home/user/updatePhotoUrl"
//    static let UPDATE_NICKNAME = "http://" + IP_ADDRESS + "/home/user/updateNickname"
//    static let UPDATE_SEX = "http://" + IP_ADDRESS + "/home/user/updateSex"
//    static let UPDATE_REGION = "http://" + IP_ADDRESS + "/home/user/updateRegion"
//    static let GET_FRIENDS_URL = "http://" + IP_ADDRESS + "/home/friend/getFriends"
//    static let SEARCH_FRIENDS_URL = "http://" + IP_ADDRESS + "/home/friend/searchFriends"
//    static let ADD_FRIENDS_URL = "http://" + IP_ADDRESS + "/home/friend/addFriend"
//    static let SEE_MONSTER_URL = "http://" + IP_ADDRESS + "/home/map/seeMonster"
//    static let GET_DANGER_WARNING_URL = "http://" + IP_ADDRESS + "/home/map/getDangerWarnings"
//    static let ACCEPT_FRIEND_URL = "http://" + IP_ADDRESS + "/home/friend/acceptFriend"
//    static let ADD_FEEDBACK_URL = "http://" + IP_ADDRESS + "/home/setting/addFeedback"
//    static let LOGOUT_URL = "http://" + IP_ADDRESS + "/home/user/logout"
//    static let UPDATE_REMARK = "http://" + IP_ADDRESS + "/home/friend/updateRemark"
//    static let PURCHASE_URL = "http://" + IP_ADDRESS + "/home/store/purchase"
//    static let UPDATE_PASSWORD_URL = "http://" + IP_ADDRESS + "/home/user/updatePassword"
//    static let REMOVE_FRIEND_URL = "http://" + IP_ADDRESS + "/home/friend/removeFriend"
//    static let UPDATE_CHANNEL_URL = "http://" + IP_ADDRESS + "/home/user/updateChannelId"
//    static let GET_FRIEND_REQUESTS_URL = "http://" + IP_ADDRESS + "/home/user/getFriendRequests"
//    static let UPDATE_USER_INFO_URL = "http://" + IP_ADDRESS + "/home/user/updateUserInfo"
    
    
    static let APP_STORE_URL = "https://itunes.apple.com/us/app/hideseek/id1154398844?ls=1&mt=8"
    static let APP_STORE_REVIEW_URL = "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=1154398844&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8"
    static let IOS7_APP_STORE_REVIEW_URL = "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=1154398844&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8"
    static let MANUAL_URL = "http://mp.weixin.qq.com/s?__biz=MzIzNzQ4MTU1NQ==&mid=100000001&idx=1&sn=5545a634716ca5fce962759fe5fb18c0&chksm=68c6ba3d5fb1332b6e0fb3080c6d94da4af57940068ef9ae2b579a88fd8f90c59e357e7ece1d&scene=18#wechat_redirect"
}
